name: LineageOS 15.1 FULL BUILD J3XNLTE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Free Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y git curl bc bison build-essential ccache \
          flex g++-multilib gcc-multilib gperf \
          lib32ncurses5-dev lib32z1-dev liblz4-tool \
          libncurses5-dev libssl-dev zip rsync \
          openjdk-8-jdk python-is-python3

      - name: Install repo
        run: |
          mkdir -p ~/bin
          curl -fsSL https://storage.googleapis.com/git-repo-downloads/repo -o ~/bin/repo
          chmod +x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Init Source
        run: |
          mkdir lineage
          cd lineage
          repo init -u https://github.com/LineageOS/android.git -b lineage-15.1 --depth=1

      - name: Clean manifests
        run: |
          cd lineage
          rm -rf .repo/local_manifests
          mkdir -p .repo/local_manifests

      - name: Add Manifest
        run: |
          cd lineage
          cat > .repo/local_manifests/j3xnlte.xml << 'EOF'
          <manifest>
            <project path="device/samsung/j3xnlte"
                     name="djeman/android_device_samsung_j3xnlte"
                     revision="lineage-15.1" />

            <project path="kernel/samsung/sharkls"
                     name="djeman/android_kernel_samsung_sharkls"
                     revision="lineage-15.1" />

            <project path="hardware/samsung"
                     name="LineageOS/android_hardware_samsung"
                     revision="lineage-15.1" />
          </manifest>
          EOF

      - name: Repo Sync
        run: |
          cd lineage
          repo sync -c --force-sync --no-tags --no-clone-bundle -j1

      - name: Build ROM
        run: |
          cd lineage
          source build/envsetup.sh
          lunch lineage_j3xnlte-userdebug
          mka bacon -j2

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: LineageOS-15.1-J3XNLTE
          path: lineage/out/target/product/j3xnlte/*.zip